name: Swift
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVELOPER_DIR: 	/Applications/Xcode_14.2.app/Contents/Developer
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.8.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
